### ISSUE TITLE
ViRogue - Local and remote administration

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/project-management#29]
This activity involves:

- the implementation of the remote control mechanism
- the security hardening of the exposed services (dashboard…)

**Comment by U039b** [comment]
We must offer a way for the administrator to open a custom port accessible from the isolated network.

After playing with `nftables`, I came to the idea of creating a custom chain we dynamically modify (not persisted).

Given this ruleset:
```nftables
flush ruleset

define iface_uplink = eth0
define iface_device = wlan0

table inet filter {
    [...]

    chain custom_chain {
    }

    chain input {
        [...]
	jump custom_chain
        [...]
    }

    chain output {
        [...]
	jump custom_chain
        [...]
    }
}
```

We open the port by inserting 2 new rules into the custom chain:
```bash
sudo nft add rule inet filter custom_chain iifname $isolated_network_iface tcp dport $port accept
sudo nft add rule inet filter custom_chain oifname $isolated_network_iface tcp sport $port tcp dport $port accept
```

We close the port by flushing the custom chain:
```bash
sudo nft flush chain inet filter custom_chain
```

**Comment by TontonSancho** [comment]
#### This month
The project is going to use grpc `proto` language to describe, generate and implement the remote/local administration. For now, only a python binding will be generated and implemented internally.

- First rpc interface design, including elementary functionalities like (get configuration, apply configuration, configuration tree querying, ...)
- Project ecosystem setups for `pirogue-admin-api`, `pirogue-admin-client` and `pirogue-admin-daemon` (included to `pirogue-admin`)
- Enhancement of `pirogue-admin` to integrate with its daemon part and new `pirogue-admin-api` rpc interface needs

#### Next month

- First alpha release of `pirogue-admin` rpc ecosystem to be able to conduct, at least, smoke tests
- A clean, safe, reliable and well documented development environment setup guide

#### Challenges

Having a fully development environment, mocked everywhere and safely, composed with debian level packages and root system level files writes, is a bit tricky

**Comment by TontonSancho** [comment]
#### This month

The `proto` definition is near feature complete as a first version.

Python `daemon` and `client` parts are partially implemented and working together. This allowed us to validate our first end-to-end transactions. For remote invocation, we use [nginx](https://nginx.org/) as reverse proxy to ensure SSL encryption. We validated that local 'insecure' and remote 'secure' calls are treated correctly. All calls are enforced by a Token authentication.

#### Next month

We will package nginx and certbot as [pirogue managed dependencies](https://github.com/PiRogueToolSuite/deb-packages/tree/virogue). The reaming features will be implemented for the `daemon` and the `client`. 

#### Challenges

The more features are implemented, the more the whole development environment is tedious to deploy and test. We should find the time to think about a 'one click' solution to test the whole ecosystem.

**Comment by TontonSancho** [comment]
#### This month
Local and remote administration are done with the following features: Dashboard configuration, Wifi configuration and VPN peers management.
Documentation includes basic commands usage and examples.
By default, remote administration is disabled. It can be enabled on private area network or publicly by providing a valid managed FQDN and an email address (both needed for certificate creation).

#### Next month
We will add quality of life command, such as system and services status, and other system management functionalities. Documentation will be polished and completed.

#### Challenges
N/A

**Comment by TontonSancho** [comment]
#### This month
PiRogue administration tool reached the release point. 
Lot of tests have been conducted, from installation to functional remote administration. Tests covers all three new PiRogue network configurations.

#### Next month
We will keep an eye on user feedback and entering in the maintenance phase.

#### Challenges
The wide variety of new PiRogue deployment scenarios was time consuming to test from end-to-end. Automating VM environment creation and management would be a significant quality-of-life improvement for our testing efforts.
