### ISSUE TITLE
ViRogue - Tests

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/project-management#30]
This activity involves testing the delivered Debian packages and the remote control mechanism: 

- on at least one cloud providers
- on VirtualBox
- on mini-PC

**Comment by CyrilBrulebois** [comment]
#### This month

The redesigned packages and the introduction of the `pirogue-admin` tool were tested repeatedly on Raspberry Pi 3, Pi 4, and Pi 5, to make sure the historical use case was still working fine. Additionally, they were tested in a virtual machine deployed on some public-facing hypervisor with the required network redirection, making it possible to validate the introduction of WireGuard support.

#### Next month

The Debian-provided Cloud image used to run tests in a virtual machine is expected to work in any QEMU/KVM-based environment, but we want to move to testing what happens with actual cloud providers. We will discuss which one(s) we want to be testing and maybe even advertise as being supported officially, and make sure everything runs fine there.

#### Challenges

None. (Except maybe how to deal with cloud account management, billing, etc.?)

**Comment by CyrilBrulebois** [comment]
#### This month
Many tests were run, using laptops, mixing wired and wireless interfaces, and testing all desktop environments that can be selected from the Debian Installer. Packages were patched incrementally to progressively support all use cases. A new page was prepared for the website in the [`virogue` branch](https://github.com/PiRogueToolSuite/piroguetoolsuite.github.io/compare/v2...virogue).

The VPN feature was also tested using a virtual machine hosted at Hetzner.

**FIXME:** Check Amazon EC2 or Microsoft Azure if possible.

#### Next month
No more work is planned.

#### Challenges
None.

**Comment by U039b** [comment]
#### This month
Many tests were run, using laptops, mixing wired and wireless interfaces, and testing all desktop environments that can be selected from the Debian Installer. The VPN feature was also tested using a virtual machine hosted at Hetzner. Tests indicate that all supported modes of operation are functional.

#### Next month
Nothing, as this task is now complete.

#### Challenges
None.
