### ISSUE TITLE
ViRogue - Documentation

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/project-management#31]
This activity involves:

- writing the documentation (concept, deployment, administration) corresponding to the different released features

**Comment by CyrilBrulebois** [comment]
#### This month

New developer-oriented pages have been written to cover the wide changes needed to support new use cases (“appliance” mode and “VPN” mode):
 - “System integration” gives an overview of the historical approach versus the new one, gives details about package-level interaction, and explains the “initial configuration” logic/heuristics.
 - “System integration — Details” gives more information about how packages can be integrated with `pirogue-admin`.
 - “System integration — Tests” details all the tests that have been performed, and sums up the (positive across the board) results.

Those additions are staged in the [`virogue` branch](https://github.com/PiRogueToolSuite/piroguetoolsuite.github.io/compare/v2...virogue), to be merged only when a release is published using the new set of packages.

#### Next month

No more work is planned on this.

#### Challenges

None.

**Comment by U039b** [comment]
#### This month
As we have released all the packages to virtualize PiRogue, the user documentation and the technical documentation have been published. This documentation covers:

* the [installation procedure](https://pts-project.org/docs/pirogue/installation/), detailing the different steps to be followed depending on the operating mode
* the [administration documentation](https://pts-project.org/docs/pirogue/version_2.x/configuration/), explaining how to configure and manage a PiRogue locally and remotely
* the documentation explaining the [technical choices](https://pts-project.org/docs/pirogue/version_2.x/system-integration/) we made for the system integration

#### Next month
Nothing, as this task is now complete.

#### Challenges
None.
